# Generated by Django 2.0.7 on 2018-07-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('unique_word_count', models.IntegerField()),
            ],
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['-unique_word_count'], name='notes_note_unique__8d07d8_idx'),
        ),
    ]
